
timezone = "local"
#timezone = "Europe/Madrid"
#timezone = "America/Havana"

[api]
enabled = true

[sources.my_source_id]
type = "file"
data_dir = "../../../../logs/var/vector/"
file_key = "file"
glob_minimum_cooldown_ms = 1_000
ignore_older_secs = 600
include = [ "../../../../logs/**/*.log" ]
max_line_bytes = 102_400
max_read_bytes = 2_048
offset_key = "offset"
read_from = "beginning"
rotate_wait_secs = 9_223

[transforms.my_transform_id]
type = "remap"
inputs = [ "my_source_id" ]
drop_on_abort = true
metric_tag_values = "single"
source = """
. = parse_json!(string!(.message))
timestamp_str = from_unix_timestamp!(.timestamp, unit: "milliseconds")
.format = format_timestamp!(timestamp_str, format: "%d/%m/%Y %H:%M:%S")
.timestamp_str = parse_timestamp!(.format, format: "%d/%m/%Y %H:%M:%S", timezone: "Etc/GMT+1")

"""

[transforms.my_transform_id2]
type = "filter"
inputs = [ "my_transform_id" ]
condition = { type = "vrl", source = """.level == "ERROR" """ }

[sinks.sink_id_1]
type = "console"
inputs = [ "my_transform_id2" ]
encoding.only_fields = ["timestamp_str", "mdc", "message"]
encoding.codec = "json"

